name: Wallenstein

on:
  schedule:
    - cron: '0 6-14 * * 1-5'
    - cron: '30 14-21 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pipeline
        id: run
        run: python main.py
        continue-on-error: true
      - name: Telegram alert
        if: steps.run.outcome == 'failure' && secrets.TELEGRAM_BOT_TOKEN && secrets.TELEGRAM_CHAT_ID
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="GitHub Actions wallenstein run failed"
